services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${OPENMAT_DATABASE__USER}
      POSTGRES_PASSWORD: ${OPENMAT_DATABASE__PASSWORD}
      POSTGRES_DB: ${OPENMAT_DATABASE__NAME}
    ports:
      - "5431:5432"
    volumes:
      - openmat_postgres_dev:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - "6380:6379"

  openmat:
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.docker

volumes:
  openmat_postgres_dev:
